version: '2'

services:
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - ${SYMFONY_PORT_HOST}:8000
    volumes:
      - ${SYMFONY_VOLUMES_HOST}:/app
    environment:
      - SYMFONY_PROJECT_NAME=${SYMFONY_PROJECT_NAME}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    depends_on:
      - ${MARIADB_HOST}
  mariadb:
    container_name: ${MARIADB_HOST}
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ${MARIADB_VOLUMES_HOST}:/bitnami/mariadb/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma2
    links:
      - ${MARIADB_HOST}
    environment:
      PMA_HOST: ${MARIADB_HOST}
      PMA_PORT: ${MARIADB_PORT_NUMBER}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
    restart: ${PMA_RESTART}
    ports:
      - ${PMA_PORT}:80
volumes:
  dbdata: